config/routes.rb
Rails.application.routes.draw do
  resources :relationships, only: [:index, :create]
  resource :address, except: [:delete, :update, :edit, :index]
  devise_for :users
  authenticated :user do
    root 'cards#index', as: :authenticated_root
  end

  # TODO Do not delete!
  # resources :users, only: [:show] do
  #   member do
  #     get :following, :followers
  #   end
  # end

  resource :my, only: [:index] do
    collection do
      get :for_sale
      get :shelf
      get :home
      get :wishlist
      get :more_shelf
      get :hidden_list
    end
  end

  resources :recommendations, only: [:index] do
    member do
      get :shelf
      get :make
    end
  end


  root 'visitor#index'
  get 'recommendation_wizard/index'
  get 'recommendation_wizard/create/:id', to: 'recommendation_wizard#create', as: 'recommendation_wizard_create'

  resources :charges
  resources :movies, path: 'movie', only: [:show] do
    collection do
      get :search
    end
    member do
      get :sale_list
      get :own
      get :wish
      get :hide
    end
  end

  mount ActionCable.server => '/cable'
  resources :notifications

  resources :people, only: [:show]
  resources :cards, path: 'movies', except: [:create, :show, :update] do
    resource :review
    resource :dvd
    resource :purchase, only: [:create]
  end

  namespace :admin do
    resources :roles
    resources :users
    resources :people
    resources :movies
  end

end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < Admin::AdminsController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def index
    @q = Movie.ransack(params[:q])
    @movies = @q.result(distinct: true).order(:title).page params[:page]
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to admin_movie_path(@movie), notice: 'Movie was successfully created.'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to admin_movie_path(@movie), notice: 'Movie was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to admin_movies_url, notice: 'Movie was successfully destroyed.' }
    end
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :summary, :poster, :language, :imdb_id, :tmdb_id, :tmdb_vote, :revenue, :budget)
    end
end

app/controllers/movies_controller.rb
class MoviesController < AuthenticatedController

  def show
    @movie = Movie.find(params[:id])
    @card = Card.for_user(current_user).where( movie: @movie).first
  end

  def sale_list
    @movie = Movie.find(params[:id])
    @q = Card.with_dvd.where(movie_id: @movie.id).ransack(params[:q])
    @cards = @q.result(distinct: true).page params[:page]
  end

  def own
    @movie = Movie.find(params[:id])
    @card = Card.find_or_create_by(movie: @movie, user: current_user)
    @card.update owns: Time.now

    respond_to do |format|
      @card.save
      format.js { render params[:show] ? "own_show" : "own_card" }
    end
  end

  def wish
    @movie = Movie.find(params[:id])
    @card = Card.find_or_create_by(movie: @movie, user: current_user)
    @card.update wish: Time.now

    respond_to do |format|
      @card.save
      format.js { render params[:show] ? "wish_show" : "wish_card" }
    end
  end

  def hide
    @movie = Movie.find(params[:id])
    @card = Card.find_or_create_by(movie: @movie, user: current_user)
    @card.update hidden: DateTime.new

    respond_to do |format|
      @card.save
      format.js { render params[:show] ? "hide_show" : "hide_card" }
    end
  end

  def search
    @search = Movie.all.ransack(params[:q])
    @movies = @search.result(distinct: true).page params[:page]
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def own?(movie)
    Card.for_user(current_user).where( movie: movie).first
  end

  def own_link(movie, card)
    if card and !card.owns.blank?
      link_to shelf_my_path do
        image_tag( 'shelf.png', class: 'star', title: "Movie is on shelf")
      end
    else
      link_to own_movie_path(movie) , remote: true , class: "own_link" do
        image_tag( 'shelf_plus.png', class: 'star', title: "Add this to shelf if you've watched this")
      end
    end
  end

  def wish_link(movie, card)
    if card and !card.wish.blank?
      link_to wishlist_my_path, remote: true, class: "wish_link" do
        image_tag( 'wishlist.png', class: 'star', title: "Now on wishlist")
      end
    else
      link_to wish_movie_path(movie), remote: true , class: "wish_link" do
        image_tag( 'wish_plus.png' , class: 'star' , title: "Add to wishlist")
      end
    end
  end

  def hide_link(movie, card)
    if card and !card.hidden.blank?
      link_to hidden_list_my_path, remote: true, class: "hide_link" do
        image_tag( 'hide_text.png', class: 'card-icon', title: "Movie hidden")
      end
    else
      link_to hide_movie_path(movie), remote: true , class: "hide_link" do
        image_tag( 'hide_text.png' , class: 'card-icon' , title: "Hide this movie")
      end
    end
  end
end

app/views/movies/_hidden_image.html.haml
=image_tag("hidden.png" , class: "img-fluid" , title: "Movie hidden")

app/views/movies/_movie.html.haml
- card_size = 'card-6' unless defined? card_size
- card = card || movie.card(current_user)

.movie-card{id: "id_#{movie.id}", class: card_size || 'card-6' }
  .movie-header
    .row
      .header-wrapper
        =link_to card_review_path(movie) do
          = image_tag '5star.png', class: 'star', :title => "Click to see all reviews for this movie"
        = wish_link(movie, card)
        = own_link(movie, card)

  .movie-content
    =link_to movie_path(movie) do
      = image_tag movie.poster.url(:medium) , class: "img-fluid rounded movie-img"

  .movie-overlay
    %h3= "#{movie.title[0 .. 12]}..."
    %p.summary.small= "#{movie.summary[0 .. 100]}..."
    .movie-actions
      = link_to sale_list_movie_path(movie) do
        = image_tag 'buy_text.png', class: 'card-icon', :title => "DVDs on sale!"

      = hide_link(movie, card)

      - if card and card.dvd
        = link_to edit_card_dvd_path(card.dvd) do
          = image_tag 'selling_text.png', class: 'card-icon', :title => "Edit your DVD for sale"
      - else
        = link_to new_card_dvd_path(movie) do
          = image_tag 'sell_text.png', class: 'card-icon', :title => "Put your DVD up for sale"

      - if card and card.review
        = link_to edit_card_review_path(card) do
          = image_tag 'reviewed_text.png', class: 'card-icon', :title => "Edit your review"
      - else
        = link_to new_card_review_path(movie) do
          = image_tag 'review_text.png', class: 'card-icon', :title => "Review this movie!"

app/views/movies/_shelf_image.html.haml
=image_tag("shelf.png" , class: "img-fluid" , title: "On shelf")

app/views/movies/hide_card.js.erb
$('#id_<%=@movie.id%>').fadeOut( 1000 )

app/views/movies/hide_show.js.erb
$('.movie-label-hide').append('<%=j render 'hidden_image'%>')
$('.add_to_hide_link').remove()

app/views/movies/index.html.haml
%h1 Home
.row
  .col-12.bg-primary.text-light
    I am looking for:
.row
  .col-8
    %br
    %h3 Recommended movies
    -# TODO make recommended movies a link
    .row
      - @movies.limit(3).each do |movie|
        .col-3
          =link_to movie_path(movie) do
            %br=image_tag(movie.poster(:medium), title: movie.title)
    %br
  .col-4
    %h3 Feed
    %ul
      %li Review
      %li Review
      %li Review
      %li Review
      %li Review
.row
  .col-12
    %h3  Your Shelf
    %br
    .row
      - current_user.discs.each do |dvd|
        .col-3
          =link_to image_tag(dvd.movie.poster(:medium), title: dvd.movie.title), dvd.movie
    %br
.row
  .col-6
    %h3 Contribution section
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
%br

app/views/movies/own.js.erb
var selling = '<%=link_to( new_card_dvd_path(@card)){ image_tag "sell_text"}%>'
$('.add_to_shelf_link').html(selling);
var image = '<%=image_tag("shelf.png" , class: "img-fluid")%>' ;
$('.movie-label').append(image)

app/views/movies/own_card.js.erb
var own_link = '<%=own_link(@movie , @card)%>' ;
$('#id_<%=@movie.id%> .own_link').html(own_link)
$('.notice').html('Added to your shelf!').show().fadeOut( 3000 )

app/views/movies/own_show.js.erb
$('.movie-label-shelf').append('<%=j render 'shelf_image'%>')
$('.add_to_shelf_link').remove()

app/views/movies/sale_list.html.haml
.row.mx-3
  .col-4
    %h5 Buy:
  .col-8
    %h5= @movie.title

.first.row
  .col-1.py-3.mx-4
    = image_tag @movie.poster.url(:thumb), class: "img-fluid" if @movie.poster?
  .col-8.py-3
    = @movie.summary
  .col-2
    = search_form_for @q,url: sale_list_movie_path(@movie) do |f|
      = f.label :price_cont
      = f.search_field :dvd_price_cont
      = f.label :condition_cont
      = f.search_field :dvd_condition_cont
      = f.submit
%br
.row
  .col-2
  .col-10
    %table
      %thead
        %tr
          %th Movie format
          %th Language
          %th Price
          %th Condition
          %th Review of user
      %tbody
        - @cards.each do |card|
          %tr
            %td DVD/Blueray/VHS
            %td English/Finnish/Swedish
            %td= card.dvd.price
            %td= card.dvd.condition
            %td review of user
            %td
              = form_for(Purchase.new , url: card_purchase_path(card)) do |f|
                =f.submit

app/views/movies/search.html.haml
.row
  .col-12
    %h3 Search results
    =sort_link(@search, :revenue, "Sort by Revenue") + " | "
    =sort_link(@search, :release_date, "Sort by Release Date")
    
.row
  - @movies.each do |movie|
    = render 'movies/movie', movie: movie

app/views/movies/show.html.haml
.movie_show
  .row
    .col-3
      = image_tag @movie.poster.url(:medium), class: "img-fluid" if @movie.poster?

    .col-6
      .row
        .col-9
          %h1= @movie.title
        .col-3
          .row
            .movie-label-hide
              -if @card and @card.hidden
                = render 'hidden_image'
            .movie-label-shelf
              -if @card and @card.owns
                = render 'shelf_image'
            .movie-label-wish
              -if @card and @card.owns
                = render 'on_wishlist_image'

        .col-12
          %p= @movie.summary
        .col-12
          %ul.list-inline
            %li= "Language: #{@movie.language}"
            %li= "Release Date #{@movie.release_date}"

          - if @card and @card.review
            = link_to edit_card_review_path(@card) do
              = image_tag 'reviewed_text.png'
          - else
            = link_to new_card_review_path(@movie) do
              = image_tag 'review_text.png'

          - if @card and @card.owns
          - else
            = link_to own_movie_path(@movie.id, show: true) , class: :add_to_shelf_link, remote: true do
              = image_tag 'add_shelf_text.png'

          - if @card and @card.wish
          - else
            = link_to wish_movie_path(@movie.id, show: true), class: :add_to_wishlist_link, remote: true do
              = image_tag 'wishlist_text.png'

          - if @card and @card.dvd
            = link_to edit_card_dvd_path(@card.dvd) do
              = image_tag 'selling_text.png'
          - else
            = link_to new_card_dvd_path(current_user) do
              = image_tag 'sell_text.png'

          - if @card and @card.hidden
          - else
            = link_to hide_movie_path(@movie.id, show: true), class: :add_to_hide_link, remote: true do
              = image_tag 'hide_text.png'

          = link_to sale_list_movie_path(@movie) do
            = image_tag 'buy_text.png'

          = link_to @movie.imdb_link, target: 'blank' do
            = image_tag 'imdb_small.png'

          = link_to @movie.tmdb_link, target: 'blank' do
            = image_tag 'tmdb_small.png'

    .col-3
      %h6= render("cards/review") if @card and @card.review

  .row.people
    - @movie.people.limit(12).each do |person|
      .col-1
        = link_to person_path(person) do
          =image_tag(person.picture(:medium), class: 'img-fluid' ,title: person.name)

app/views/movies/wish.js.erb
var wish_link = '<%=wish_link(@movie, @card)%>';
$('#id_<%=@movie.id%> .wish_link').html(wish_link)
$('.notice').html('Added to your wishlist!').show().fadeOut( 3000 )

app/views/movies/wish_card.js.erb
var wish_link = '<%=wish_link(@movie, @card)%>';
$('#id_<%=@movie.id%> .wish_link').html(wish_link)
$('.notice').html('Added to your wishlist!').show().fadeOut( 3000 )