config/routes.rb
Rails.application.routes.draw do
  resources :relationships, only: [:index, :create]
  resource :address, except: [:delete, :update, :edit, :index]
  devise_for :users
  authenticated :user do
    root 'cards#index', as: :authenticated_root
  end

  # TODO Do not delete!
  # resources :users, only: [:show] do
  #   member do
  #     get :following, :followers
  #   end
  # end

  resource :my, only: [:index] do
    collection do
      get :for_sale
      get :shelf
      get :home
      get :wishlist
      get :more_shelf
      get :hidden_list
    end
  end

  resources :recommendations, only: [:index] do
    member do
      get :shelf
      get :make
    end
  end


  root 'visitor#index'
  get 'recommendation_wizard/index'
  get 'recommendation_wizard/create/:id', to: 'recommendation_wizard#create', as: 'recommendation_wizard_create'

  resources :charges
  resources :movies, path: 'movie', only: [:show] do
    collection do
      get :search
    end
    member do
      get :sale_list
      get :own
      get :wish
      get :hide
    end
  end

  mount ActionCable.server => '/cable'
  resources :notifications

  resources :people, only: [:show]
  resources :cards, path: 'movies', except: [:create, :show, :update] do
    resource :review
    resource :dvd
    resource :purchase, only: [:create]
  end

  namespace :admin do
    resources :roles
    resources :users
    resources :people
    resources :movies
  end

end

app/models/role.rb
class Role < ApplicationRecord
  validates :person_name, :character_name, :movie_id, presence: true
  belongs_to :movie
  belongs_to :person, optional: true
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::AdminsController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  def index
    @q = Role.ransack(params[:q])
    @roles = @q.result(distinct: true).order(:person_name).page params[:page]
  end

  def show
  end

  def new
    @role = Role.new
  end

  def edit
  end

  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to admin_role_path(@role), notice: 'Role was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to admin_role_path(@role), notice: 'Role was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
    end
  end

  private
    def set_role
      @role = Role.find(params[:id])
    end

    def role_params
      params.require(:role).permit(:person_name, :character_name, :person_id, :movie_id)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  def index
    @roles = Role.all
  end

  def show
  end

  def new
    @role = Role.new
  end

  def edit
  end

  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
    end
  end

  private
    def set_role
      @role = Role.find(params[:id])
    end

    def role_params
      params.require(:role).permit(:person_name, :character_name, :person_id, :movie_id)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/admin/roles/_form.html.haml
= simple_form_for(@role) do |f|
  = f.error_notification

  .form-inputs
    = f.input :person_name
    = f.input :character_name
    = f.input :person_id
    = f.input :movie_id

  .form-actions
    = f.button :submit

app/views/admin/roles/edit.html.haml
%h1 Editing role

= render 'form'

= link_to 'Show', @role
\|
= link_to 'Back', admin_roles_path

app/views/admin/roles/index.html.haml
%h1 Listing roles
= paginate @roles
%table
  %thead
    %tr
      %th Person name
      %th Character name
      %th Person
      %th Movie

  %tbody
    - @roles.each do |role|
      %tr
        %td= role.person_name
        %td= role.character_name
        %td= role.person_id
        %td= role.movie_id
        %td= link_to 'Show', admin_role_path(role)
        %td= link_to 'Edit', edit_admin_role_path(role)

%br

= link_to 'New Role', new_admin_role_path

app/views/admin/roles/new.html.haml
%h1 New role

= render 'form'

= link_to 'Back', admin_roles_path

app/views/admin/roles/show.html.haml
%p#notice= notice

%p
  %b Person name:
  = @role.person_name
%p
  %b Character name:
  = @role.character_name
%p
  %b Person:
  = @role.person_id
%p
  %b Movie:
  = @role.movie_id

= link_to 'Edit', edit_admin_role_path(@role)
\|
= link_to 'Back', admin_roles_path