config/routes.rb
Rails.application.routes.draw do
  resources :relationships, only: [:index, :create]
  resource :address, except: [:delete, :update, :edit, :index]
  devise_for :users
  authenticated :user do
    root 'cards#index', as: :authenticated_root
  end

  # TODO Do not delete!
  # resources :users, only: [:show] do
  #   member do
  #     get :following, :followers
  #   end
  # end

  resource :my, only: [:index] do
    collection do
      get :for_sale
      get :shelf
      get :home
      get :wishlist
      get :more_shelf
      get :hidden_list
    end
  end

  resources :recommendations, only: [:index] do
    member do
      get :shelf
      get :make
    end
  end


  root 'visitor#index'
  get 'recommendation_wizard/index'
  get 'recommendation_wizard/create/:id', to: 'recommendation_wizard#create', as: 'recommendation_wizard_create'

  resources :charges
  resources :movies, path: 'movie', only: [:show] do
    collection do
      get :search
    end
    member do
      get :sale_list
      get :own
      get :wish
      get :hide
    end
  end

  mount ActionCable.server => '/cable'
  resources :notifications

  resources :people, only: [:show]
  resources :cards, path: 'movies', except: [:create, :show, :update] do
    resource :review
    resource :dvd
    resource :purchase, only: [:create]
  end

  namespace :admin do
    resources :roles
    resources :users
    resources :people
    resources :movies
  end

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  belongs_to :recommendation, required: false
  belongs_to :dvd, required: false
  belongs_to :review, required: false
  scope :visible, -> { where(hidden: nil) }
  scope :wishlist, -> { visible.where.not(wish: nil) }
  scope :owned, -> { visible.where.not(owns: nil)}
  scope :for_user, ->(user) { where(user: user) }
  scope :with_dvd, -> {where.not(dvd_id: nil)}
  scope :hidden, -> { where.not(hidden: nil)}
  has_many :notifications, as: :object
  
  def add_dvd(dvd)
    self.dvd = dvd
    self.selling = Time.now if self.dvd.price > 0
    save
  end

  def add_review(review)
    self.review = review
    save
  end

end

app/controllers/cards_controller.rb
class CardsController < AuthenticatedController
  before_action :set_card, except: [:index, :new]

  def index
    card_amount = current_user.cards.length
    if card_amount < 5
      notice = flash.notice
      redirect_to recommendation_wizard_index_path, notice: "#{notice} Add #{5 - card_amount} movies to get started!"
    else
      @cards = Card.visible.includes(:movie).for_user(current_user).limit(4)
    end

    @cards_on_wishlist = Card.wishlist.for_user(current_user).limit(20)

    @cards_for_sale = Card.visible.owned.for_user(current_user).where.not(selling: nil)

    card_ids = Card.where(user_id: current_user.id).pluck(:movie_id)
    @movies = Movie.where.not(id: card_ids)
    @movies = @movies.order(revenue: :desc).page(params[:page])
  end

  def show
  end

  def edit
  end

  def create
    @card = Card.new(user: current_user, movie: @movie)
    respond_to do |format|
      if @card.save
        format.html { redirect_to movie_path(@movie), notice: 'Card was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to movie_path(@movie), notice: 'Card was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
    end
  end



  private

  def set_card
    @card = Card.find(params[:id])
    if @card.user != current_user
      redirect_to cards_url
    end
  end
end

app/views/cards/_review.html.haml
%h6
  %strong Your review for this movie:
%hr
.container
  .row
    %dt Plot score:
  .row
    %dd
      =@card.review.plot_score
      &mdash;
      =@card.review.plot_comment
  .row
    %dt Acting score:
  .row
    %dd
      =@card.review.acting_score
      &mdash;
      =@card.review.acting_comment

  %hr
  .row
    .col-7
    .col-4
      = link_to 'Edit my review', edit_card_review_path(@card), class: "btn btn-light"

app/views/cards/_social.html.haml
.social.bg-light
  %h3 Notifications
  .notifications
    = render user_notifications
    

app/views/cards/index.html.haml
.col-12.index-gallery
  .gallery-title-top
    %h1=link_to 'Recommendations', recommendations_path
    %h4 Tell us your preferences and we can make better recommendations for you
  .flickity1
    -@movies.each do |movie|
      =render 'movies/movie', movie: movie, card_size: 'card-6'
-# .col-3
  =render 'social' TODO Move to navbar dropdown

.col-12.index-gallery
  -if @cards_on_wishlist.empty?
    .empty-wishlist.empty
      %h1 You haven't added any movies to your wishlist yet.
      %h4=link_to "Why not make a start? Go to recommendations.", recommendations_path
  -else
    .gallery-title
      %h1=link_to "Wishlist", wishlist_my_path
      %h4 Add movies to your wishlist and we'll notify you when they're for sale
    .flickity2
      -@cards_on_wishlist.each do |card|
        = render 'movies/movie', movie: card.movie, card: card

.col-12.index-gallery
  -if @cards_for_sale.empty?
    .empty-sale.empty
      %h1 You aren't selling any movies yet.
      %h4=link_to "Got some movies you want to sell? Search for the movie and add it to your shelf to begin.", recommendations_path
  -else
    .gallery-title
      %h1=link_to 'DVD Shelf', for_sale_my_path
      %h4 View and edit your DVDs for sale
    .flickity3
      -@cards_for_sale.each do |card|
        = render 'movies/movie', movie: card.movie, card: card




:javascript
  var options =  {
      cellAlign: 'left',
      contains: true,
      pageDots: false,
      wrapAround: false,
      groupCells: true
    };
  new Flickity( document.querySelector(".flickity1") ,  {
      cellAlign: 'left',
      contains: true,
      pageDots: false,
      wrapAround: false,
      groupCells: true
    } );
  new Flickity( document.querySelector(".flickity2") ,  {
      cellAlign: 'left',
      contains: true,
      pageDots: false,
      wrapAround: false,
      groupCells: true
    } );
  new Flickity( document.querySelector(".flickity3") ,  {
      cellAlign: 'left',
      contains: true,
      pageDots: false,
      wrapAround: false,
      groupCells: true
    } );

app/views/cards/more_shelf.js.erb
// $('#shelf').html("<%= escape_javascript(render @cards) %>");
<% @cards.each do |card| %>
  $('#shelf').append("<%= escape_javascript(render card) %>");
  jQuery('#shelf > .movie-card').first().remove();
<%end%>

<% if @cards.next_page %>
  <%link =link_to '[more]', cards_more_shelf_path(page: @cards.next_page), remote: true%>
  $('.shelf_link').html("<%= escape_javascript(link) %>");
<% else %>
  $('.shelf_link').remove();
<% end %>