config/routes.rb
Rails.application.routes.draw do
  resources :relationships, only: [:index, :create]
  resource :address, except: [:delete, :update, :edit, :index]
  devise_for :users
  authenticated :user do
    root 'cards#index', as: :authenticated_root
  end

  # TODO Do not delete!
  # resources :users, only: [:show] do
  #   member do
  #     get :following, :followers
  #   end
  # end

  resource :my, only: [:index] do
    collection do
      get :for_sale
      get :shelf
      get :home
      get :wishlist
      get :more_shelf
      get :hidden_list
    end
  end

  resources :recommendations, only: [:index] do
    member do
      get :shelf
      get :make
    end
  end


  root 'visitor#index'
  get 'recommendation_wizard/index'
  get 'recommendation_wizard/create/:id', to: 'recommendation_wizard#create', as: 'recommendation_wizard_create'

  resources :charges
  resources :movies, path: 'movie', only: [:show] do
    collection do
      get :search
    end
    member do
      get :sale_list
      get :own
      get :wish
      get :hide
    end
  end

  mount ActionCable.server => '/cable'
  resources :notifications

  resources :people, only: [:show]
  resources :cards, path: 'movies', except: [:create, :show, :update] do
    resource :review
    resource :dvd
    resource :purchase, only: [:create]
  end

  namespace :admin do
    resources :roles
    resources :users
    resources :people
    resources :movies
  end

end

app/models/person.rb
class Person < ApplicationRecord
  validates :name, presence: true
  has_attached_file :picture, styles: { thumb: "100x150!",
                                      medium: "300x450!",
                                      large: "600X900!"},
                    default_url: "/images/person/picture/:style.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  validates :tmdb_id, numericality:{ only_integer: true, greater_than_or_equal_to: 0 }
  has_many :roles, -> {includes :movie}
  has_many :movies, :through => :roles

  attr_reader :picture_remote_url

  def picture_remote_url=(url_value)
    self.picture = URI.parse(url_value)
    @picture_remote_url = url_value
  end

  def imdb_link
    "http://www.imdb.com/name/#{self.imdb_id}"
  end
  def tmdb_link
    "https://www.themoviedb.org/person/#{self.tmdb_id}"
  end
end

app/controllers/admin/people_controller.rb
class Admin::PeopleController < Admin::AdminsController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @q = Person.ransack(params[:q])
    @people = @q.result(distinct: true).order(:name).page params[:page]
  end

  def show
  end

  def new
    @person = Person.new
  end

  def edit
  end

  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to admin_person_path(@person), notice: 'Person was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to admin_person_path(@person), notice: 'Person was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to admin_people_url, notice: 'Person was successfully destroyed.' }
    end
  end

  private
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:name, :bio, :picture, :tmdb_id, :imdb_id,
                                    :birthday, :born_in)
    end
end

app/controllers/people_controller.rb
class PeopleController < AuthenticatedController

  def show
    @person = Person.find(params[:id])
  end
end

app/controllers/person_controller.rb
class PersonController < AuthenticatedController

  def show
    @person = Person.find(params[:id])
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/admin/people/_form.html.haml
= simple_form_for([:admin, @person]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :bio
    = f.input :tmdb_id
    = f.input :imdb_id
    = f.input :birthday
    = f.input :born_in
    = f.input :picture, as: :file
  .form-actions
    = f.button :submit

app/views/admin/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', admin_people_path(@person)
\|
= link_to 'Back', admin_people_path

app/views/admin/people/index.html.haml
%h1 Listing people

%p on browser... /admin/people
= paginate @people
= search_form_for [:admin, @q] do |f|
  = f.label :name_cont
  = f.search_field :name_cont

  = f.label :imdb_id_cont
  = f.search_field :imdb_id_cont

  = f.label :tmdb_id_eq
  = f.search_field :tmdb_id_eq
  = f.submit

%table
  %thead
    %tr
      %th Picture
      %th Name
      %th Bio
      %th imdb_id
      %th Tmdb Id
      %th Birthday
      %th born_in

  %tbody
    - @people.each do |person|
      %tr
        %td= image_tag person.picture.url(:thumb)
        %td= person.name
        %td= person.bio.to_s[0..200]
        %td= link_to 'imdb', person.imdb_link, target: :blank
        %td= link_to 'tmdb', person.tmdb_link, target: :blank
        %td= person.birthday
        %td= person.born_in
        %td= link_to 'Show', admin_person_path(person)

%br
= paginate @people
= link_to 'New Person', new_admin_person_path

app/views/admin/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', admin_people_path

app/views/admin/people/show.html.haml
%p#notice= notice
.row
  .col-12.col-sm-6.col-md-4.col-lg-3.col-xl-2
    = image_tag @person.picture.url(:medium), class: 'img-fluid'
  .col-12.col-sm-6.col-md-8.col-lg-9.col-xl-10
    %p
      %b Name:
      = @person.name
    %p
      %b Bio:
      = @person.bio
    %p
      %b imdb_id:
      = @person.imdb_id
    %p
      %b tmdb_id:
      = @person.tmdb_id
    %p
      %b Birthday:
      = @person.birthday
    %p
      %b Born In:
      = @person.born_in
.row
  -@person.roles.each do |role|
    = link_to image_tag(role.movie.poster(:thumb), title: role.movie.title), admin_movie_path(role.movie_id)
  %table
    %thead
      %tr
        %th Film
        %th Role
    %tbody
      - @person.roles.each do |role|
        %tr
          %td= role.movie.title
          %td= role.character_name

= link_to 'Edit', edit_admin_person_path(@person)
\|
= link_to 'Back', admin_people_path